//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdminMenu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminMenu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SchoolManagement.AdminMenu", typeof(AdminMenu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool label4_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label4.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Century Gothic, Size=11.25, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        public static System.Drawing.Font label4_Font {
            get {
                object obj = ResourceManager.GetObject("label4.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode label4_ImeMode {
            get {
                object obj = ResourceManager.GetObject("label4.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=210,Y=248}.
        /// </summary>
        public static System.Drawing.Point label4_Location {
            get {
                object obj = ResourceManager.GetObject("label4.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=573, Height=20}.
        /// </summary>
        public static System.Drawing.Size label4_Size {
            get {
                object obj = ResourceManager.GetObject("label4.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 29.
        /// </summary>
        public static int label4_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label4.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --------------------------------------------------ACTIONS--------------------------------------------------.
        /// </summary>
        public static string label4_Text {
            get {
                return ResourceManager.GetString("label4.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.ContentAlignment similar to MiddleCenter.
        /// </summary>
        public static System.Drawing.ContentAlignment label4_TextAlign {
            get {
                object obj = ResourceManager.GetObject("label4.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool lbClasses_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lbClasses.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Century Gothic, Size=11.25, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        public static System.Drawing.Font lbClasses_Font {
            get {
                object obj = ResourceManager.GetObject("lbClasses.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode lbClasses_ImeMode {
            get {
                object obj = ResourceManager.GetObject("lbClasses.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=883,Y=412}.
        /// </summary>
        public static System.Drawing.Point lbClasses_Location {
            get {
                object obj = ResourceManager.GetObject("lbClasses.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=135, Height=20}.
        /// </summary>
        public static System.Drawing.Size lbClasses_Size {
            get {
                object obj = ResourceManager.GetObject("lbClasses.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 18.
        /// </summary>
        public static int lbClasses_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lbClasses.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLASS MANAGER.
        /// </summary>
        public static string lbClasses_Text {
            get {
                return ResourceManager.GetString("lbClasses.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool lbDep_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lbDep.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Century Gothic, Size=11.25, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        public static System.Drawing.Font lbDep_Font {
            get {
                object obj = ResourceManager.GetObject("lbDep.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode lbDep_ImeMode {
            get {
                object obj = ResourceManager.GetObject("lbDep.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=183, Height=20}.
        /// </summary>
        public static System.Drawing.Size lbDep_Size {
            get {
                object obj = ResourceManager.GetObject("lbDep.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 14.
        /// </summary>
        public static int lbDep_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lbDep.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEPARTMENT MANAGER.
        /// </summary>
        public static string lbDep_Text {
            get {
                return ResourceManager.GetString("lbDep.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool lbHello_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lbHello.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Century Gothic, Size=11.25, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        public static System.Drawing.Font lbHello_Font {
            get {
                object obj = ResourceManager.GetObject("lbHello.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode lbHello_ImeMode {
            get {
                object obj = ResourceManager.GetObject("lbHello.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=12,Y=9}.
        /// </summary>
        public static System.Drawing.Point lbHello_Location {
            get {
                object obj = ResourceManager.GetObject("lbHello.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=99, Height=20}.
        /// </summary>
        public static System.Drawing.Size lbHello_Size {
            get {
                object obj = ResourceManager.GetObject("lbHello.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 16.
        /// </summary>
        public static int lbHello_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lbHello.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, Admin.
        /// </summary>
        public static string lbHello_Text {
            get {
                return ResourceManager.GetString("lbHello.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool lbLogout_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lbLogout.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Century Gothic, Size=11.25, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        public static System.Drawing.Font lbLogout_Font {
            get {
                object obj = ResourceManager.GetObject("lbLogout.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode lbLogout_ImeMode {
            get {
                object obj = ResourceManager.GetObject("lbLogout.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=760,Y=578}.
        /// </summary>
        public static System.Drawing.Point lbLogout_Location {
            get {
                object obj = ResourceManager.GetObject("lbLogout.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=71, Height=20}.
        /// </summary>
        public static System.Drawing.Size lbLogout_Size {
            get {
                object obj = ResourceManager.GetObject("lbLogout.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 20.
        /// </summary>
        public static int lbLogout_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lbLogout.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGOUT.
        /// </summary>
        public static string lbLogout_Text {
            get {
                return ResourceManager.GetString("lbLogout.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool lbProfile_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lbProfile.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Century Gothic, Size=11.25, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        public static System.Drawing.Font lbProfile_Font {
            get {
                object obj = ResourceManager.GetObject("lbProfile.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode lbProfile_ImeMode {
            get {
                object obj = ResourceManager.GetObject("lbProfile.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=76,Y=412}.
        /// </summary>
        public static System.Drawing.Point lbProfile_Location {
            get {
                object obj = ResourceManager.GetObject("lbProfile.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=93, Height=20}.
        /// </summary>
        public static System.Drawing.Size lbProfile_Size {
            get {
                object obj = ResourceManager.GetObject("lbProfile.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 12.
        /// </summary>
        public static int lbProfile_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lbProfile.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY PROFILE.
        /// </summary>
        public static string lbProfile_Text {
            get {
                return ResourceManager.GetString("lbProfile.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool lbStudents_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lbStudents.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Century Gothic, Size=11.25, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        public static System.Drawing.Font lbStudents_Font {
            get {
                object obj = ResourceManager.GetObject("lbStudents.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode lbStudents_ImeMode {
            get {
                object obj = ResourceManager.GetObject("lbStudents.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=291,Y=412}.
        /// </summary>
        public static System.Drawing.Point lbStudents_Location {
            get {
                object obj = ResourceManager.GetObject("lbStudents.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=156, Height=20}.
        /// </summary>
        public static System.Drawing.Size lbStudents_Size {
            get {
                object obj = ResourceManager.GetObject("lbStudents.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 4.
        /// </summary>
        public static int lbStudents_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lbStudents.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STUDENTS MANAGER.
        /// </summary>
        public static string lbStudents_Text {
            get {
                return ResourceManager.GetString("lbStudents.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool lbSubjects_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lbSubjects.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Century Gothic, Size=11.25, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        public static System.Drawing.Font lbSubjects_Font {
            get {
                object obj = ResourceManager.GetObject("lbSubjects.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode lbSubjects_ImeMode {
            get {
                object obj = ResourceManager.GetObject("lbSubjects.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=141,Y=578}.
        /// </summary>
        public static System.Drawing.Point lbSubjects_Location {
            get {
                object obj = ResourceManager.GetObject("lbSubjects.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=157, Height=20}.
        /// </summary>
        public static System.Drawing.Size lbSubjects_Size {
            get {
                object obj = ResourceManager.GetObject("lbSubjects.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 10.
        /// </summary>
        public static int lbSubjects_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lbSubjects.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUBJECTS MANAGER.
        /// </summary>
        public static string lbSubjects_Text {
            get {
                return ResourceManager.GetString("lbSubjects.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool lbTeachers_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lbTeachers.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Century Gothic, Size=11.25, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        public static System.Drawing.Font lbTeachers_Font {
            get {
                object obj = ResourceManager.GetObject("lbTeachers.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode lbTeachers_ImeMode {
            get {
                object obj = ResourceManager.GetObject("lbTeachers.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=572,Y=412}.
        /// </summary>
        public static System.Drawing.Point lbTeachers_Location {
            get {
                object obj = ResourceManager.GetObject("lbTeachers.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=161, Height=20}.
        /// </summary>
        public static System.Drawing.Size lbTeachers_Size {
            get {
                object obj = ResourceManager.GetObject("lbTeachers.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 6.
        /// </summary>
        public static int lbTeachers_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lbTeachers.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEACHERS MANAGER.
        /// </summary>
        public static string lbTeachers_Text {
            get {
                return ResourceManager.GetString("lbTeachers.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool lbTotalClass_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lbTotalClass.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Century Gothic, Size=26.25, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        public static System.Drawing.Font lbTotalClass_Font {
            get {
                object obj = ResourceManager.GetObject("lbTotalClass.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode lbTotalClass_ImeMode {
            get {
                object obj = ResourceManager.GetObject("lbTotalClass.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=686,Y=141}.
        /// </summary>
        public static System.Drawing.Point lbTotalClass_Location {
            get {
                object obj = ResourceManager.GetObject("lbTotalClass.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=38, Height=41}.
        /// </summary>
        public static System.Drawing.Size lbTotalClass_Size {
            get {
                object obj = ResourceManager.GetObject("lbTotalClass.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 27.
        /// </summary>
        public static int lbTotalClass_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lbTotalClass.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string lbTotalClass_Text {
            get {
                return ResourceManager.GetString("lbTotalClass.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool lbToTalStudent_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lbToTalStudent.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Century Gothic, Size=26.25, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        public static System.Drawing.Font lbToTalStudent_Font {
            get {
                object obj = ResourceManager.GetObject("lbToTalStudent.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode lbToTalStudent_ImeMode {
            get {
                object obj = ResourceManager.GetObject("lbToTalStudent.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=163,Y=141}.
        /// </summary>
        public static System.Drawing.Point lbToTalStudent_Location {
            get {
                object obj = ResourceManager.GetObject("lbToTalStudent.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=38, Height=41}.
        /// </summary>
        public static System.Drawing.Size lbToTalStudent_Size {
            get {
                object obj = ResourceManager.GetObject("lbToTalStudent.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 25.
        /// </summary>
        public static int lbToTalStudent_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lbToTalStudent.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string lbToTalStudent_Text {
            get {
                return ResourceManager.GetString("lbToTalStudent.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool lbTotalSubject_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lbTotalSubject.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Century Gothic, Size=26.25, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        public static System.Drawing.Font lbTotalSubject_Font {
            get {
                object obj = ResourceManager.GetObject("lbTotalSubject.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode lbTotalSubject_ImeMode {
            get {
                object obj = ResourceManager.GetObject("lbTotalSubject.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=932,Y=141}.
        /// </summary>
        public static System.Drawing.Point lbTotalSubject_Location {
            get {
                object obj = ResourceManager.GetObject("lbTotalSubject.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=38, Height=41}.
        /// </summary>
        public static System.Drawing.Size lbTotalSubject_Size {
            get {
                object obj = ResourceManager.GetObject("lbTotalSubject.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 28.
        /// </summary>
        public static int lbTotalSubject_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lbTotalSubject.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string lbTotalSubject_Text {
            get {
                return ResourceManager.GetString("lbTotalSubject.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool lbTotalTeacher_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lbTotalTeacher.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Century Gothic, Size=26.25, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        public static System.Drawing.Font lbTotalTeacher_Font {
            get {
                object obj = ResourceManager.GetObject("lbTotalTeacher.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode lbTotalTeacher_ImeMode {
            get {
                object obj = ResourceManager.GetObject("lbTotalTeacher.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=417,Y=141}.
        /// </summary>
        public static System.Drawing.Point lbTotalTeacher_Location {
            get {
                object obj = ResourceManager.GetObject("lbTotalTeacher.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=38, Height=41}.
        /// </summary>
        public static System.Drawing.Size lbTotalTeacher_Size {
            get {
                object obj = ResourceManager.GetObject("lbTotalTeacher.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 26.
        /// </summary>
        public static int lbTotalTeacher_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lbTotalTeacher.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string lbTotalTeacher_Text {
            get {
                return ResourceManager.GetString("lbTotalTeacher.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        public static bool menu1_Enabled {
            get {
                object obj = ResourceManager.GetObject("menu1.Enabled", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode menu1_ImeMode {
            get {
                object obj = ResourceManager.GetObject("menu1.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=98,Y=54}.
        /// </summary>
        public static System.Drawing.Point menu1_Location {
            get {
                object obj = ResourceManager.GetObject("menu1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=186, Height=147}.
        /// </summary>
        public static System.Drawing.Size menu1_Size {
            get {
                object obj = ResourceManager.GetObject("menu1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 21.
        /// </summary>
        public static int menu1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("menu1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Color similar to Color [Empty].
        /// </summary>
        public static System.Drawing.Color menu1_Values_ImageTransparentColor {
            get {
                object obj = ResourceManager.GetObject("menu1.Values.ImageTransparentColor", resourceCulture);
                return ((System.Drawing.Color)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL STUDENT.
        /// </summary>
        public static string menu1_Values_Text {
            get {
                return ResourceManager.GetString("menu1.Values.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        public static bool menu2_Enabled {
            get {
                object obj = ResourceManager.GetObject("menu2.Enabled", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode menu2_ImeMode {
            get {
                object obj = ResourceManager.GetObject("menu2.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=349,Y=54}.
        /// </summary>
        public static System.Drawing.Point menu2_Location {
            get {
                object obj = ResourceManager.GetObject("menu2.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=186, Height=147}.
        /// </summary>
        public static System.Drawing.Size menu2_Size {
            get {
                object obj = ResourceManager.GetObject("menu2.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Color similar to Color [Empty].
        /// </summary>
        public static System.Drawing.Color menu2_Values_ImageTransparentColor {
            get {
                object obj = ResourceManager.GetObject("menu2.Values.ImageTransparentColor", resourceCulture);
                return ((System.Drawing.Color)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL TEACHER.
        /// </summary>
        public static string menu2_Values_Text {
            get {
                return ResourceManager.GetString("menu2.Values.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        public static bool menu3_Enabled {
            get {
                object obj = ResourceManager.GetObject("menu3.Enabled", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode menu3_ImeMode {
            get {
                object obj = ResourceManager.GetObject("menu3.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=612,Y=54}.
        /// </summary>
        public static System.Drawing.Point menu3_Location {
            get {
                object obj = ResourceManager.GetObject("menu3.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=186, Height=147}.
        /// </summary>
        public static System.Drawing.Size menu3_Size {
            get {
                object obj = ResourceManager.GetObject("menu3.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 23.
        /// </summary>
        public static int menu3_TabIndex {
            get {
                object obj = ResourceManager.GetObject("menu3.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Color similar to Color [Empty].
        /// </summary>
        public static System.Drawing.Color menu3_Values_ImageTransparentColor {
            get {
                object obj = ResourceManager.GetObject("menu3.Values.ImageTransparentColor", resourceCulture);
                return ((System.Drawing.Color)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL CLASS.
        /// </summary>
        public static string menu3_Values_Text {
            get {
                return ResourceManager.GetString("menu3.Values.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        public static bool menu4_Enabled {
            get {
                object obj = ResourceManager.GetObject("menu4.Enabled", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode menu4_ImeMode {
            get {
                object obj = ResourceManager.GetObject("menu4.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=847,Y=54}.
        /// </summary>
        public static System.Drawing.Point menu4_Location {
            get {
                object obj = ResourceManager.GetObject("menu4.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=186, Height=147}.
        /// </summary>
        public static System.Drawing.Size menu4_Size {
            get {
                object obj = ResourceManager.GetObject("menu4.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 24.
        /// </summary>
        public static int menu4_TabIndex {
            get {
                object obj = ResourceManager.GetObject("menu4.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Color similar to Color [Empty].
        /// </summary>
        public static System.Drawing.Color menu4_Values_ImageTransparentColor {
            get {
                object obj = ResourceManager.GetObject("menu4.Values.ImageTransparentColor", resourceCulture);
                return ((System.Drawing.Color)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL SUBJECT.
        /// </summary>
        public static string menu4_Values_Text {
            get {
                return ResourceManager.GetString("menu4.Values.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pbClasses_Image {
            get {
                object obj = ResourceManager.GetObject("pbClasses.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode pbClasses_ImeMode {
            get {
                object obj = ResourceManager.GetObject("pbClasses.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=887,Y=284}.
        /// </summary>
        public static System.Drawing.Point pbClasses_Location {
            get {
                object obj = ResourceManager.GetObject("pbClasses.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=136, Height=125}.
        /// </summary>
        public static System.Drawing.Size pbClasses_Size {
            get {
                object obj = ResourceManager.GetObject("pbClasses.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.PictureBoxSizeMode similar to Zoom.
        /// </summary>
        public static System.Windows.Forms.PictureBoxSizeMode pbClasses_SizeMode {
            get {
                object obj = ResourceManager.GetObject("pbClasses.SizeMode", resourceCulture);
                return ((System.Windows.Forms.PictureBoxSizeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 7.
        /// </summary>
        public static int pbClasses_TabIndex {
            get {
                object obj = ResourceManager.GetObject("pbClasses.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pbDepartment_Image {
            get {
                object obj = ResourceManager.GetObject("pbDepartment.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode pbDepartment_ImeMode {
            get {
                object obj = ResourceManager.GetObject("pbDepartment.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=452,Y=450}.
        /// </summary>
        public static System.Drawing.Point pbDepartment_Location {
            get {
                object obj = ResourceManager.GetObject("pbDepartment.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=120, Height=125}.
        /// </summary>
        public static System.Drawing.Size pbDepartment_Size {
            get {
                object obj = ResourceManager.GetObject("pbDepartment.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.PictureBoxSizeMode similar to Zoom.
        /// </summary>
        public static System.Windows.Forms.PictureBoxSizeMode pbDepartment_SizeMode {
            get {
                object obj = ResourceManager.GetObject("pbDepartment.SizeMode", resourceCulture);
                return ((System.Windows.Forms.PictureBoxSizeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 13.
        /// </summary>
        public static int pbDepartment_TabIndex {
            get {
                object obj = ResourceManager.GetObject("pbDepartment.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pbLogout_Image {
            get {
                object obj = ResourceManager.GetObject("pbLogout.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode pbLogout_ImeMode {
            get {
                object obj = ResourceManager.GetObject("pbLogout.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=760,Y=450}.
        /// </summary>
        public static System.Drawing.Point pbLogout_Location {
            get {
                object obj = ResourceManager.GetObject("pbLogout.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=118, Height=125}.
        /// </summary>
        public static System.Drawing.Size pbLogout_Size {
            get {
                object obj = ResourceManager.GetObject("pbLogout.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.PictureBoxSizeMode similar to Zoom.
        /// </summary>
        public static System.Windows.Forms.PictureBoxSizeMode pbLogout_SizeMode {
            get {
                object obj = ResourceManager.GetObject("pbLogout.SizeMode", resourceCulture);
                return ((System.Windows.Forms.PictureBoxSizeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 19.
        /// </summary>
        public static int pbLogout_TabIndex {
            get {
                object obj = ResourceManager.GetObject("pbLogout.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pbProfile_Image {
            get {
                object obj = ResourceManager.GetObject("pbProfile.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode pbProfile_ImeMode {
            get {
                object obj = ResourceManager.GetObject("pbProfile.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=69,Y=284}.
        /// </summary>
        public static System.Drawing.Point pbProfile_Location {
            get {
                object obj = ResourceManager.GetObject("pbProfile.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=123, Height=125}.
        /// </summary>
        public static System.Drawing.Size pbProfile_Size {
            get {
                object obj = ResourceManager.GetObject("pbProfile.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.PictureBoxSizeMode similar to Zoom.
        /// </summary>
        public static System.Windows.Forms.PictureBoxSizeMode pbProfile_SizeMode {
            get {
                object obj = ResourceManager.GetObject("pbProfile.SizeMode", resourceCulture);
                return ((System.Windows.Forms.PictureBoxSizeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 11.
        /// </summary>
        public static int pbProfile_TabIndex {
            get {
                object obj = ResourceManager.GetObject("pbProfile.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pbStudents_Image {
            get {
                object obj = ResourceManager.GetObject("pbStudents.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode pbStudents_ImeMode {
            get {
                object obj = ResourceManager.GetObject("pbStudents.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=314,Y=284}.
        /// </summary>
        public static System.Drawing.Point pbStudents_Location {
            get {
                object obj = ResourceManager.GetObject("pbStudents.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=114, Height=125}.
        /// </summary>
        public static System.Drawing.Size pbStudents_Size {
            get {
                object obj = ResourceManager.GetObject("pbStudents.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.PictureBoxSizeMode similar to Zoom.
        /// </summary>
        public static System.Windows.Forms.PictureBoxSizeMode pbStudents_SizeMode {
            get {
                object obj = ResourceManager.GetObject("pbStudents.SizeMode", resourceCulture);
                return ((System.Windows.Forms.PictureBoxSizeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        public static int pbStudents_TabIndex {
            get {
                object obj = ResourceManager.GetObject("pbStudents.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pbSubjects_Image {
            get {
                object obj = ResourceManager.GetObject("pbSubjects.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode pbSubjects_ImeMode {
            get {
                object obj = ResourceManager.GetObject("pbSubjects.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=170,Y=450}.
        /// </summary>
        public static System.Drawing.Point pbSubjects_Location {
            get {
                object obj = ResourceManager.GetObject("pbSubjects.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=114, Height=125}.
        /// </summary>
        public static System.Drawing.Size pbSubjects_Size {
            get {
                object obj = ResourceManager.GetObject("pbSubjects.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.PictureBoxSizeMode similar to Zoom.
        /// </summary>
        public static System.Windows.Forms.PictureBoxSizeMode pbSubjects_SizeMode {
            get {
                object obj = ResourceManager.GetObject("pbSubjects.SizeMode", resourceCulture);
                return ((System.Windows.Forms.PictureBoxSizeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 9.
        /// </summary>
        public static int pbSubjects_TabIndex {
            get {
                object obj = ResourceManager.GetObject("pbSubjects.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pbTeachers_Image {
            get {
                object obj = ResourceManager.GetObject("pbTeachers.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode pbTeachers_ImeMode {
            get {
                object obj = ResourceManager.GetObject("pbTeachers.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=588,Y=284}.
        /// </summary>
        public static System.Drawing.Point pbTeachers_Location {
            get {
                object obj = ResourceManager.GetObject("pbTeachers.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=120, Height=125}.
        /// </summary>
        public static System.Drawing.Size pbTeachers_Size {
            get {
                object obj = ResourceManager.GetObject("pbTeachers.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.PictureBoxSizeMode similar to Zoom.
        /// </summary>
        public static System.Windows.Forms.PictureBoxSizeMode pbTeachers_SizeMode {
            get {
                object obj = ResourceManager.GetObject("pbTeachers.SizeMode", resourceCulture);
                return ((System.Windows.Forms.PictureBoxSizeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 5.
        /// </summary>
        public static int pbTeachers_TabIndex {
            get {
                object obj = ResourceManager.GetObject("pbTeachers.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pictureBox1_Image {
            get {
                object obj = ResourceManager.GetObject("pictureBox1.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode pictureBox1_ImeMode {
            get {
                object obj = ResourceManager.GetObject("pictureBox1.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=939,Y=125}.
        /// </summary>
        public static System.Drawing.Point pictureBox1_Location {
            get {
                object obj = ResourceManager.GetObject("pictureBox1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=175, Height=168}.
        /// </summary>
        public static System.Drawing.Size pictureBox1_Size {
            get {
                object obj = ResourceManager.GetObject("pictureBox1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.PictureBoxSizeMode similar to Zoom.
        /// </summary>
        public static System.Windows.Forms.PictureBoxSizeMode pictureBox1_SizeMode {
            get {
                object obj = ResourceManager.GetObject("pictureBox1.SizeMode", resourceCulture);
                return ((System.Windows.Forms.PictureBoxSizeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 30.
        /// </summary>
        public static int pictureBox1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("pictureBox1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pictureBox2_Image {
            get {
                object obj = ResourceManager.GetObject("pictureBox2.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode pictureBox2_ImeMode {
            get {
                object obj = ResourceManager.GetObject("pictureBox2.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=375,Y=-82}.
        /// </summary>
        public static System.Drawing.Point pictureBox2_Location {
            get {
                object obj = ResourceManager.GetObject("pictureBox2.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=197, Height=239}.
        /// </summary>
        public static System.Drawing.Size pictureBox2_Size {
            get {
                object obj = ResourceManager.GetObject("pictureBox2.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.PictureBoxSizeMode similar to Zoom.
        /// </summary>
        public static System.Windows.Forms.PictureBoxSizeMode pictureBox2_SizeMode {
            get {
                object obj = ResourceManager.GetObject("pictureBox2.SizeMode", resourceCulture);
                return ((System.Windows.Forms.PictureBoxSizeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 31.
        /// </summary>
        public static int pictureBox2_TabIndex {
            get {
                object obj = ResourceManager.GetObject("pictureBox2.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pictureBox3_Image {
            get {
                object obj = ResourceManager.GetObject("pictureBox3.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode pictureBox3_ImeMode {
            get {
                object obj = ResourceManager.GetObject("pictureBox3.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=-47,Y=125}.
        /// </summary>
        public static System.Drawing.Point pictureBox3_Location {
            get {
                object obj = ResourceManager.GetObject("pictureBox3.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=158, Height=127}.
        /// </summary>
        public static System.Drawing.Size pictureBox3_Size {
            get {
                object obj = ResourceManager.GetObject("pictureBox3.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.PictureBoxSizeMode similar to Zoom.
        /// </summary>
        public static System.Windows.Forms.PictureBoxSizeMode pictureBox3_SizeMode {
            get {
                object obj = ResourceManager.GetObject("pictureBox3.SizeMode", resourceCulture);
                return ((System.Windows.Forms.PictureBoxSizeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 32.
        /// </summary>
        public static int pictureBox3_TabIndex {
            get {
                object obj = ResourceManager.GetObject("pictureBox3.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pictureBox4_Image {
            get {
                object obj = ResourceManager.GetObject("pictureBox4.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode pictureBox4_ImeMode {
            get {
                object obj = ResourceManager.GetObject("pictureBox4.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=42,Y=555}.
        /// </summary>
        public static System.Drawing.Point pictureBox4_Location {
            get {
                object obj = ResourceManager.GetObject("pictureBox4.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=67, Height=87}.
        /// </summary>
        public static System.Drawing.Size pictureBox4_Size {
            get {
                object obj = ResourceManager.GetObject("pictureBox4.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.PictureBoxSizeMode similar to Zoom.
        /// </summary>
        public static System.Windows.Forms.PictureBoxSizeMode pictureBox4_SizeMode {
            get {
                object obj = ResourceManager.GetObject("pictureBox4.SizeMode", resourceCulture);
                return ((System.Windows.Forms.PictureBoxSizeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 33.
        /// </summary>
        public static int pictureBox4_TabIndex {
            get {
                object obj = ResourceManager.GetObject("pictureBox4.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pictureBox5_Image {
            get {
                object obj = ResourceManager.GetObject("pictureBox5.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode pictureBox5_ImeMode {
            get {
                object obj = ResourceManager.GetObject("pictureBox5.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=939,Y=504}.
        /// </summary>
        public static System.Drawing.Point pictureBox5_Location {
            get {
                object obj = ResourceManager.GetObject("pictureBox5.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=137, Height=104}.
        /// </summary>
        public static System.Drawing.Size pictureBox5_Size {
            get {
                object obj = ResourceManager.GetObject("pictureBox5.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.PictureBoxSizeMode similar to Zoom.
        /// </summary>
        public static System.Windows.Forms.PictureBoxSizeMode pictureBox5_SizeMode {
            get {
                object obj = ResourceManager.GetObject("pictureBox5.SizeMode", resourceCulture);
                return ((System.Windows.Forms.PictureBoxSizeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 34.
        /// </summary>
        public static int pictureBox5_TabIndex {
            get {
                object obj = ResourceManager.GetObject("pictureBox5.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pictureBox6_Image {
            get {
                object obj = ResourceManager.GetObject("pictureBox6.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode pictureBox6_ImeMode {
            get {
                object obj = ResourceManager.GetObject("pictureBox6.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=-61,Y=403}.
        /// </summary>
        public static System.Drawing.Point pictureBox6_Location {
            get {
                object obj = ResourceManager.GetObject("pictureBox6.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=92, Height=108}.
        /// </summary>
        public static System.Drawing.Size pictureBox6_Size {
            get {
                object obj = ResourceManager.GetObject("pictureBox6.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.PictureBoxSizeMode similar to Zoom.
        /// </summary>
        public static System.Windows.Forms.PictureBoxSizeMode pictureBox6_SizeMode {
            get {
                object obj = ResourceManager.GetObject("pictureBox6.SizeMode", resourceCulture);
                return ((System.Windows.Forms.PictureBoxSizeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 35.
        /// </summary>
        public static int pictureBox6_TabIndex {
            get {
                object obj = ResourceManager.GetObject("pictureBox6.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
    }
}
